# Generated by Django 4.1 on 2022-12-01 15:40

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('animalName', models.CharField(max_length=50, unique=True)),
                ('imageURl', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('approved', 'Approved'), ('delivered', 'Delivered')], default='placed', max_length=10)),
                ('category', models.CharField(choices=[('mammal', 'Mammal'), ('fish', 'Fish'), ('bird', 'Bird'), ('reptile', 'Reptile'), ('amphibian', 'Amphibian')], default='mammal', max_length=10)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
