# Generated by Django 4.1 on 2022-12-02 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_animal_animalname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animalName',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only letters allowed!')]),
        ),
    ]
